# dxf_processor.py — DEPRECATED
#
# This module used naive string matching ("LINE" in line) to count DXF
# entities. That counts substrings inside POLYLINE, SPLINE, headers etc.
# and silently swallows all exceptions.
#
# It was replaced by src/hermes/dxf.py (SLICE-001) which uses the
# battle-tested ezdxf library and fails loudly on bad input.
#
# Scheduled for removal in a later slice after all callers have been
# migrated. Do NOT extend this module.
import warnings
from pathlib import Path

from hermes.dxf import parse as _real_parse


def parse_dxf_summary(file_path: str) -> None:
    """DEPRECATED — use hermes.dxf.parse() instead."""
    warnings.warn(
        "dxf_processor.parse_dxf_summary is deprecated; "
        "use hermes.dxf.parse() which uses ezdxf for real parsing.",
        DeprecationWarning,
        stacklevel=2,
    )
    geom = _real_parse(Path(file_path))
    report = f"""
# GEOMETRY AUDIT REPORT (RSB1164) — generated by hermes.dxf
- **Source**: {geom.source_path}
- **Entities (total)**: {geom.entity_count}
- **Lines**: {geom.lines}
- **Arcs**: {geom.arcs}
- **Polylines**: {geom.polylines}
- **Bounding box**: min={geom.bbox_min}, max={geom.bbox_max}
- **Width**: {geom.width_mm:.3f} mm
- **Height**: {geom.height_mm:.3f} mm
- **Parser**: ezdxf 1.4.3 (real, not string-matching)
"""
    Path("GEOMETRY_AUDIT_REPORT.md").write_text(report, encoding="utf-8")
    print(
        f"[HERMES DXF] {geom.entity_count} entities "
        f"(lines={geom.lines} arcs={geom.arcs} polylines={geom.polylines})."
    )


if __name__ == "__main__":
    parse_dxf_summary("attached_assets/Drawing1_1774780944987.dxf")
