#!/usr/bin/env node
/**
 * SAI Rolotech Engine - Setup Wizard
 * Guided setup for first-time users
 */

import chalk from "chalk";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ASCII Art
const ASCII_LOGO = `
╔═══════════════════════════════════════════════════════════╗
║                                                           ║
║     ██████╗ ██████╗ ███╗   ███╗███████╗██╗ ██████╗       ║
║    ██╔════╝██╔═══██╗████╗ ████║██╔════╝██║██╔════╝       ║
║    ██║     ██║   ██║██╔████╔██║███████╗██║██║  ███╗      ║
║    ██║     ██║   ██║██║╚██╔╝██║╚════██║██║██║   ██║      ║
║    ╚██████╗╚██████╔╝██║ ╚═╝ ██║███████║██║╚██████╔╝      ║
║     ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚═╝ ╚═════╝       ║
║                                                           ║
║         🤖 SMART ENGINE v1.0 - Setup Wizard               ║
║                                                           ║
╚═══════════════════════════════════════════════════════════╝
`;

// Questions
const QUESTIONS = [
  {
    key: "ANTHROPIC_API_KEY",
    prompt: "Anthropic API Key (for Claude):",
    hint: "Get from https://console.anthropic.com",
    required: true,
  },
  {
    key: "TELEGRAM_BOT_TOKEN",
    prompt: "Telegram Bot Token (optional):",
    hint: "Get from @BotFather on Telegram",
    required: false,
  },
  {
    key: "DISCORD_BOT_TOKEN",
    prompt: "Discord Bot Token (optional):",
    hint: "Get from Discord Developer Portal",
    required: false,
  },
  {
    key: "TAVILY_API_KEY",
    prompt: "Tavily API Key for Web Search (optional):",
    hint: "Get from https://tavily.com",
    required: false,
  },
  {
    key: "OPENAI_API_KEY",
    prompt: "OpenAI API Key (for DALL-E, TTS):",
    hint: "Get from https://platform.openai.com",
    required: false,
  },
];

async function askQuestion(question) {
  console.log(chalk.cyan(`\n${question.prompt}`));
  if (question.hint) {
    console.log(chalk.gray(`  Hint: ${question.hint}`));
  }

  const rl = await import("readline").then((m) =>
    m.createInterface({ input: process.stdin, output: process.stdout })
  );

  return new Promise((resolve) => {
    rl.question(chalk.yellow("  > "), (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function setup() {
  console.clear();
  console.log(chalk.cyan(ASCII_LOGO));

  console.log(chalk.white("\n  Welcome to SAI Rolotech Engine Setup!\n"));
  console.log(
    chalk.gray("  This wizard will help you configure your AI engine.\n")
  );

  // Create directories
  console.log(chalk.cyan("📁 Creating directories..."));
  const dirs = ["data", "data/memory", "data/whatsapp", "temp"];
  for (const dir of dirs) {
    mkdirSync(dir, { recursive: true });
  }
  console.log(chalk.green("  ✅ Directories created\n"));

  // Load existing .env if exists
  let existingConfig = {};
  if (existsSync(".env")) {
    console.log(chalk.cyan("📋 Loading existing .env file..."));
    const content = readFileSync(".env", "utf8");
    for (const line of content.split("\n")) {
      const [key, ...valueParts] = line.split("=");
      if (key && valueParts.length > 0) {
        existingConfig[key.trim()] = valueParts.join("=").trim();
      }
    }
    console.log(chalk.green("  ✅ Loaded\n"));
  }

  // Ask questions
  const newConfig = { ...existingConfig };
  for (const question of QUESTIONS) {
    const answer = await askQuestion(question);
    if (answer) {
      newConfig[question.key] = answer;
    } else if (question.required && !existingConfig[question.key]) {
      console.log(chalk.red(`  ⚠️  Required! Please provide a value.`));
      const retry = await askQuestion(question);
      newConfig[question.key] = retry || "";
    }
  }

  // Generate .env file
  console.log(chalk.cyan("\n💾 Saving configuration..."));
  let envContent = `# SAI Rolotech Engine Configuration
# Generated by setup wizard

`;

  for (const [key, value] of Object.entries(newConfig)) {
    if (value) {
      envContent += `${key}=${value}\n`;
    }
  }

  writeFileSync(".env", envContent);
  console.log(chalk.green("  ✅ Saved to .env\n"));

  // Show completion
  console.log(chalk.green(`
╔═══════════════════════════════════════════════════════════╗
║                    ✅ SETUP COMPLETE!                    ║
╚═══════════════════════════════════════════════════════════╝
`));

  console.log(chalk.white("\n  What's next?\n"));
  console.log(chalk.cyan("  1. ") + chalk.white("Start the engine: ") + chalk.yellow("npm run dev"));
  console.log(chalk.cyan("  2. ") + chalk.white("Open dashboard at: ") + chalk.yellow("http://localhost:3000"));
  console.log(chalk.cyan("  3. ") + chalk.white("Chat with AI in terminal: ") + chalk.yellow("npm run chat\n"));

  console.log(chalk.gray("  Available commands:"));
  console.log(chalk.gray("    /start          - Start bot (Telegram)"));
  console.log(chalk.gray("    /help           - Show help (Telegram)"));
  console.log(chalk.gray("    /code           - Write code"));
  console.log(chalk.gray("    /cad            - AutoCAD help"));
  console.log(chalk.gray("    /search         - Web search"));
  console.log(chalk.gray("    /image          - Generate image\n"));

  console.log(chalk.green("  Happy building! 🚀\n"));
}

// Run setup
setup().catch((err) => {
  console.error(chalk.red("Setup failed:"), err);
  process.exit(1);
});
